DROP TABLE foglalas CASCADE CONSTRAINTS;

DROP TABLE helyszin CASCADE CONSTRAINTS;

DROP TABLE oktato CASCADE CONSTRAINTS;

DROP TABLE oktato_kijeloles CASCADE CONSTRAINTS;

DROP TABLE resztvevo_torles CASCADE CONSTRAINTS;

DROP TABLE tanfolyam CASCADE CONSTRAINTS;

DROP TABLE tanfolyam_ertekeles CASCADE CONSTRAINTS;

DROP TABLE tanfolyam_tipus CASCADE CONSTRAINTS;

DROP TABLE tanfolyam_tipus_arvaltozas CASCADE CONSTRAINTS;

DROP TABLE tanfolyam_torles CASCADE CONSTRAINTS;

DROP TABLE telefonos_megerosites CASCADE CONSTRAINTS;

DROP TABLE ugyfel CASCADE CONSTRAINTS;