DROP TABLE szallito CASCADE CONSTRAINTS;

DROP TABLE szallitoi_rendeles CASCADE CONSTRAINTS;

DROP TABLE szallitoi_rendeles_sor CASCADE CONSTRAINTS;

DROP TABLE szamla CASCADE CONSTRAINTS;

DROP TABLE termek CASCADE CONSTRAINTS;

DROP TABLE termekjegyzek CASCADE CONSTRAINTS;

DROP TABLE termekosztaly CASCADE CONSTRAINTS;

DROP TABLE utalas CASCADE CONSTRAINTS;

DROP TABLE vasarloi_rendeles CASCADE CONSTRAINTS;

DROP TABLE vasarloi_rendeles_sor CASCADE CONSTRAINTS;

DROP TABLE vevo CASCADE CONSTRAINTS;